const FRAMEWORK_WEB_COMPONENTS_ALIAS = 'webcomponents';
const FRAMEWORK_ANGULAR_ALIAS = 'angular';
const FRAMEWORK_REACT_ALIAS = 'react';

const FRAMEWORKS_ALIAS = [
  FRAMEWORK_WEB_COMPONENTS_ALIAS,
  FRAMEWORK_ANGULAR_ALIAS,
  FRAMEWORK_REACT_ALIAS,
];

const FRAMEWORKS_DIR_MAP = new Map([
  [FRAMEWORK_WEB_COMPONENTS_ALIAS, 'web-components'],
  [FRAMEWORK_ANGULAR_ALIAS, 'angular'],
  [FRAMEWORK_REACT_ALIAS, 'react'],
]);

const DIR_CLIENT_MAIN_ALIAS = 'client';
const DIR_CLIENT_TEMP_ALIAS = 'client-temp';

const DIRS_MAP = new Map([
  [DIR_CLIENT_MAIN_ALIAS, DIR_CLIENT_MAIN_ALIAS],
  [DIR_CLIENT_TEMP_ALIAS, DIR_CLIENT_TEMP_ALIAS],
]);

module.exports = {
  FRAMEWORK_WEB_COMPONENTS_ALIAS,
  FRAMEWORK_ANGULAR_ALIAS,
  FRAMEWORK_REACT_ALIAS,
  FRAMEWORKS_ALIAS,
  FRAMEWORKS_DIR_MAP,
  DIR_CLIENT_MAIN_ALIAS,
  DIR_CLIENT_TEMP_ALIAS,
  DIRS_MAP,
};
